version: "2"
linters:
  default: all
  disable:
    # unused
    - nlreturn
    - exhaustruct
    - depguard
    - nonamedreturns
    - forbidigo
  exclusions:
    rules:
      - linters:
          - funlen
          - goconst
          - wsl
          - errcheck
        path: .+_test.go

  settings:
    gosec:
      excludes:
        - G304
        - G115
    gocritic:
      enable-all: true
      disabled-checks:
        - whyNoLint
        - commentedOutCode
      settings:
        unnamedResult:
          checkExported: true
    errcheck:
      check-type-assertions: true
      check-blank: false
      disable-default-exclusions: false
      exclude-functions:
      - (*os.File).Close
      - os.RemoveAll
      - os.Remove
      - os.Chtimes
      - (io.Closer).Close
      - (*compress/gzip.Reader).Close
      - (*archive/zip.ReadCloser).Close
      - (*github.com/bodgit/sevenzip.ReadCloser).Close
      - (*github.com/nwaples/rardecode.ReadCloser).Close

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports

